#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AmbienceSoundController

#include "Basic.hpp"

#include "AmbienceSoundController_classes.hpp"
#include "AmbienceSoundController_parameters.hpp"


namespace SDK
{

// Function AmbienceSoundController.AmbienceSoundController_C.ExecuteUbergraph_AmbienceSoundController
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAmbienceSoundController_C::ExecuteUbergraph_AmbienceSoundController(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AmbienceSoundController_C", "ExecuteUbergraph_AmbienceSoundController");

	Params::AmbienceSoundController_C_ExecuteUbergraph_AmbienceSoundController Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AmbienceSoundController.AmbienceSoundController_C.StartMusic
// (BlueprintCallable, BlueprintEvent)

void AAmbienceSoundController_C::StartMusic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AmbienceSoundController_C", "StartMusic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AmbienceSoundController.AmbienceSoundController_C.AlarmTriggeredInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void AAmbienceSoundController_C::AlarmTriggeredInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AmbienceSoundController_C", "AlarmTriggeredInterfaceCall");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AmbienceSoundController.AmbienceSoundController_C.StartSound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerCharacter_C*               Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAmbienceSoundController_C::StartSound(class APlayerCharacter_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AmbienceSoundController_C", "StartSound");

	Params::AmbienceSoundController_C_StartSound Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AmbienceSoundController.AmbienceSoundController_C.StopOutsideSound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerCharacter_C*               Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAmbienceSoundController_C::StopOutsideSound(class APlayerCharacter_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AmbienceSoundController_C", "StopOutsideSound");

	Params::AmbienceSoundController_C_StopOutsideSound Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AmbienceSoundController.AmbienceSoundController_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAmbienceSoundController_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AmbienceSoundController_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AmbienceSoundController.AmbienceSoundController_C.AlarmDisabledInterfaceCall
// (Public, BlueprintCallable, BlueprintEvent)

void AAmbienceSoundController_C::AlarmDisabledInterfaceCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AmbienceSoundController_C", "AlarmDisabledInterfaceCall");

	UObject::ProcessEvent(Func, nullptr);
}

}

