#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Armor_Light

#include "Basic.hpp"

#include "Armor_Light_classes.hpp"
#include "Armor_Light_parameters.hpp"


namespace SDK
{

// Function Armor_Light.Armor_Light_C.InitiateHeal__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void AArmor_Light_C::InitiateHeal__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Armor_Light_C", "InitiateHeal__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Armor_Light.Armor_Light_C.ExecuteUbergraph_Armor_Light
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AArmor_Light_C::ExecuteUbergraph_Armor_Light(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Armor_Light_C", "ExecuteUbergraph_Armor_Light");

	Params::Armor_Light_C_ExecuteUbergraph_Armor_Light Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Armor_Light.Armor_Light_C.HealArmor
// (BlueprintCallable, BlueprintEvent)

void AArmor_Light_C::HealArmor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Armor_Light_C", "HealArmor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Armor_Light.Armor_Light_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AArmor_Light_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Armor_Light_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Armor_Light.Armor_Light_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AArmor_Light_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Armor_Light_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Armor_Light.Armor_Light_C.DamageArmor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   HealthDamage                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AArmor_Light_C::DamageArmor(int32 Damage, int32* HealthDamage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Armor_Light_C", "DamageArmor");

	Params::Armor_Light_C_DamageArmor Parms{};

	Parms.Damage = Damage;

	UObject::ProcessEvent(Func, &Parms);

	if (HealthDamage != nullptr)
		*HealthDamage = Parms.HealthDamage;
}


// Function Armor_Light.Armor_Light_C.ChangeState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AArmor_Light_C::ChangeState(int32 State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Armor_Light_C", "ChangeState");

	Params::Armor_Light_C_ChangeState Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}

}

