#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameOverUI

#include "Basic.hpp"

#include "GameOverUI_classes.hpp"
#include "GameOverUI_parameters.hpp"


namespace SDK
{

// Function GameOverUI.GameOverUI_C.ExecuteUbergraph_GameOverUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGameOverUI_C::ExecuteUbergraph_GameOverUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameOverUI_C", "ExecuteUbergraph_GameOverUI");

	Params::GameOverUI_C_ExecuteUbergraph_GameOverUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GameOverUI.GameOverUI_C.DestroyPlayers
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void UGameOverUI_C::DestroyPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameOverUI_C", "DestroyPlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameOverUI.GameOverUI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UGameOverUI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameOverUI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameOverUI.GameOverUI_C.BndEvt__GameOverUI_Button_0_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UGameOverUI_C::BndEvt__GameOverUI_Button_0_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameOverUI_C", "BndEvt__GameOverUI_Button_0_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameOverUI.GameOverUI_C.BndEvt__GameOverUI_Button_2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UGameOverUI_C::BndEvt__GameOverUI_Button_2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameOverUI_C", "BndEvt__GameOverUI_Button_2_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GameOverUI.GameOverUI_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UGameOverUI_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameOverUI_C", "GetText_0");

	Params::GameOverUI_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

