#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JoiningGameUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function JoiningGameUI.JoiningGameUI_C.ExecuteUbergraph_JoiningGameUI
// 0x0004 (0x0004 - 0x0000)
struct JoiningGameUI_C_ExecuteUbergraph_JoiningGameUI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(JoiningGameUI_C_ExecuteUbergraph_JoiningGameUI) == 0x000004, "Wrong alignment on JoiningGameUI_C_ExecuteUbergraph_JoiningGameUI");
static_assert(sizeof(JoiningGameUI_C_ExecuteUbergraph_JoiningGameUI) == 0x000004, "Wrong size on JoiningGameUI_C_ExecuteUbergraph_JoiningGameUI");
static_assert(offsetof(JoiningGameUI_C_ExecuteUbergraph_JoiningGameUI, EntryPoint) == 0x000000, "Member 'JoiningGameUI_C_ExecuteUbergraph_JoiningGameUI::EntryPoint' has a wrong offset!");

}

