#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LeaveGameConfirm

#include "Basic.hpp"

#include "LeaveGameConfirm_classes.hpp"
#include "LeaveGameConfirm_parameters.hpp"


namespace SDK
{

// Function LeaveGameConfirm.LeaveGameConfirm_C.ExecuteUbergraph_LeaveGameConfirm
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULeaveGameConfirm_C::ExecuteUbergraph_LeaveGameConfirm(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LeaveGameConfirm_C", "ExecuteUbergraph_LeaveGameConfirm");

	Params::LeaveGameConfirm_C_ExecuteUbergraph_LeaveGameConfirm Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LeaveGameConfirm.LeaveGameConfirm_C.BndEvt__LeaveGameConfirm_Button_100_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULeaveGameConfirm_C::BndEvt__LeaveGameConfirm_Button_100_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LeaveGameConfirm_C", "BndEvt__LeaveGameConfirm_Button_100_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LeaveGameConfirm.LeaveGameConfirm_C.BndEvt__LeaveGameConfirm_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULeaveGameConfirm_C::BndEvt__LeaveGameConfirm_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LeaveGameConfirm_C", "BndEvt__LeaveGameConfirm_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

