#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LockpickComponent

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LockpickComponent.LockpickComponent_C
// 0x0010 (0x00C0 - 0x00B0)
class ULockpickComponent_C final : public UActorComponent
{
public:
	FMulticastInlineDelegateProperty_             Unlock;                                            // 0x00B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Unlock__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LockpickComponent_C">();
	}
	static class ULockpickComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULockpickComponent_C>();
	}
};
static_assert(alignof(ULockpickComponent_C) == 0x000008, "Wrong alignment on ULockpickComponent_C");
static_assert(sizeof(ULockpickComponent_C) == 0x0000C0, "Wrong size on ULockpickComponent_C");
static_assert(offsetof(ULockpickComponent_C, Unlock) == 0x0000B0, "Member 'ULockpickComponent_C::Unlock' has a wrong offset!");

}

