#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapBuyUI

#include "Basic.hpp"

#include "MapBuyUI_classes.hpp"
#include "MapBuyUI_parameters.hpp"


namespace SDK
{

// Function MapBuyUI.MapBuyUI_C.ExecuteUbergraph_MapBuyUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapBuyUI_C::ExecuteUbergraph_MapBuyUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "ExecuteUbergraph_MapBuyUI");

	Params::MapBuyUI_C_ExecuteUbergraph_MapBuyUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapBuyUI.MapBuyUI_C.CoinsChangedupdate
// (BlueprintCallable, BlueprintEvent)

void UMapBuyUI_C::CoinsChangedupdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "CoinsChangedupdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapBuyUI.MapBuyUI_C.BndEvt__MapBuyUI_CashBuyButton_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMapBuyUI_C::BndEvt__MapBuyUI_CashBuyButton_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "BndEvt__MapBuyUI_CashBuyButton_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapBuyUI.MapBuyUI_C.BndEvt__MapBuyUI_CashBuyButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMapBuyUI_C::BndEvt__MapBuyUI_CashBuyButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "BndEvt__MapBuyUI_CashBuyButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapBuyUI.MapBuyUI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMapBuyUI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapBuyUI.MapBuyUI_C.BuyMap
// (BlueprintCallable, BlueprintEvent)

void UMapBuyUI_C::BuyMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "BuyMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapBuyUI.MapBuyUI_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapBuyUI_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "GetText_0");

	Params::MapBuyUI_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapBuyUI.MapBuyUI_C.GetText_1
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMapBuyUI_C::GetText_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "GetText_1");

	Params::MapBuyUI_C_GetText_1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MapBuyUI.MapBuyUI_C.HiddenWhenPurchased
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UMapBuyUI_C::HiddenWhenPurchased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapBuyUI_C", "HiddenWhenPurchased");

	Params::MapBuyUI_C_HiddenWhenPurchased Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

