#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPCClothing_Hoodie

#include "Basic.hpp"

#include "NPCClothing_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPCClothing_Hoodie.NPCClothing_Hoodie_C
// 0x0000 (0x0258 - 0x0258)
class ANPCClothing_Hoodie_C final : public ANPCClothing_base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPCClothing_Hoodie_C">();
	}
	static class ANPCClothing_Hoodie_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPCClothing_Hoodie_C>();
	}
};
static_assert(alignof(ANPCClothing_Hoodie_C) == 0x000008, "Wrong alignment on ANPCClothing_Hoodie_C");
static_assert(sizeof(ANPCClothing_Hoodie_C) == 0x000258, "Wrong size on ANPCClothing_Hoodie_C");

}

