#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OfficeBuilding_Round

#include "Basic.hpp"

#include "OfficeBuilding_Round_classes.hpp"
#include "OfficeBuilding_Round_parameters.hpp"


namespace SDK
{

// Function OfficeBuilding_Round.OfficeBuilding_Round_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AOfficeBuilding_Round_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OfficeBuilding_Round_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

