#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PowerboxProgress

#include "Basic.hpp"

#include "PowerboxProgress_classes.hpp"
#include "PowerboxProgress_parameters.hpp"


namespace SDK
{

// Function PowerboxProgress.PowerboxProgress_C.ExecuteUbergraph_PowerboxProgress
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerboxProgress_C::ExecuteUbergraph_PowerboxProgress(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerboxProgress_C", "ExecuteUbergraph_PowerboxProgress");

	Params::PowerboxProgress_C_ExecuteUbergraph_PowerboxProgress Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerboxProgress.PowerboxProgress_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPowerboxProgress_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerboxProgress_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerboxProgress.PowerboxProgress_C.GetPercent_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UPowerboxProgress_C::GetPercent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerboxProgress_C", "GetPercent_0");

	Params::PowerboxProgress_C_GetPercent_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

