#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SensingActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SensingActor.SensingActor_C
// 0x0018 (0x0298 - 0x0280)
class ASensingActor_C final : public APawn
{
public:
	class UArrowComponent*                        Arrow;                                             // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPawnSensingComponent*                  PawnSensing;                                       // 0x0288(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SensingActor_C">();
	}
	static class ASensingActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASensingActor_C>();
	}
};
static_assert(alignof(ASensingActor_C) == 0x000008, "Wrong alignment on ASensingActor_C");
static_assert(sizeof(ASensingActor_C) == 0x000298, "Wrong size on ASensingActor_C");
static_assert(offsetof(ASensingActor_C, Arrow) == 0x000280, "Member 'ASensingActor_C::Arrow' has a wrong offset!");
static_assert(offsetof(ASensingActor_C, PawnSensing) == 0x000288, "Member 'ASensingActor_C::PawnSensing' has a wrong offset!");
static_assert(offsetof(ASensingActor_C, DefaultSceneRoot) == 0x000290, "Member 'ASensingActor_C::DefaultSceneRoot' has a wrong offset!");

}

