#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Setup_Jewellery_1

#include "Basic.hpp"

#include "Setup_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Setup_Jewellery_1.Setup_Jewellery_1_C
// 0x0000 (0x02A0 - 0x02A0)
class ASetup_Jewellery_1_C final : public ASetup_base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Setup_Jewellery_1_C">();
	}
	static class ASetup_Jewellery_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASetup_Jewellery_1_C>();
	}
};
static_assert(alignof(ASetup_Jewellery_1_C) == 0x000008, "Wrong alignment on ASetup_Jewellery_1_C");
static_assert(sizeof(ASetup_Jewellery_1_C) == 0x0002A0, "Wrong size on ASetup_Jewellery_1_C");

}

