#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShakeDrill

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShakeDrill.ShakeDrill_C
// 0x0000 (0x01B0 - 0x01B0)
class UShakeDrill_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ShakeDrill_C">();
	}
	static class UShakeDrill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShakeDrill_C>();
	}
};
static_assert(alignof(UShakeDrill_C) == 0x000010, "Wrong alignment on UShakeDrill_C");
static_assert(sizeof(UShakeDrill_C) == 0x0001B0, "Wrong size on UShakeDrill_C");

}

