#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShopItem_Mask_Panda

#include "Basic.hpp"

#include "ShopItem_Mask_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShopItem_Mask_Panda.ShopItem_Mask_Panda_C
// 0x0000 (0x0270 - 0x0270)
class AShopItem_Mask_Panda_C final : public AShopItem_Mask_base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ShopItem_Mask_Panda_C">();
	}
	static class AShopItem_Mask_Panda_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShopItem_Mask_Panda_C>();
	}
};
static_assert(alignof(AShopItem_Mask_Panda_C) == 0x000008, "Wrong alignment on AShopItem_Mask_Panda_C");
static_assert(sizeof(AShopItem_Mask_Panda_C) == 0x000270, "Wrong size on AShopItem_Mask_Panda_C");

}

