#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShopItem_Map_Museum

#include "Basic.hpp"

#include "ShopItem_Map_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShopItem_Map_Museum.ShopItem_Map_Museum_C
// 0x0000 (0x02C0 - 0x02C0)
class AShopItem_Map_Museum_C final : public AShopItem_Map_base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ShopItem_Map_Museum_C">();
	}
	static class AShopItem_Map_Museum_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShopItem_Map_Museum_C>();
	}
};
static_assert(alignof(AShopItem_Map_Museum_C) == 0x000008, "Wrong alignment on AShopItem_Map_Museum_C");
static_assert(sizeof(AShopItem_Map_Museum_C) == 0x0002C0, "Wrong size on AShopItem_Map_Museum_C");

}

