#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_DeadlyAim_Tier3

#include "Basic.hpp"


namespace SDK::Params
{

// Function Skill_DeadlyAim_Tier3.Skill_DeadlyAim_Tier3_C.ExecuteUbergraph_Skill_DeadlyAim_Tier3
// 0x0004 (0x0004 - 0x0000)
struct Skill_DeadlyAim_Tier3_C_ExecuteUbergraph_Skill_DeadlyAim_Tier3 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_DeadlyAim_Tier3_C_ExecuteUbergraph_Skill_DeadlyAim_Tier3) == 0x000004, "Wrong alignment on Skill_DeadlyAim_Tier3_C_ExecuteUbergraph_Skill_DeadlyAim_Tier3");
static_assert(sizeof(Skill_DeadlyAim_Tier3_C_ExecuteUbergraph_Skill_DeadlyAim_Tier3) == 0x000004, "Wrong size on Skill_DeadlyAim_Tier3_C_ExecuteUbergraph_Skill_DeadlyAim_Tier3");
static_assert(offsetof(Skill_DeadlyAim_Tier3_C_ExecuteUbergraph_Skill_DeadlyAim_Tier3, EntryPoint) == 0x000000, "Member 'Skill_DeadlyAim_Tier3_C_ExecuteUbergraph_Skill_DeadlyAim_Tier3::EntryPoint' has a wrong offset!");

}

