#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteamAchievementComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SteamAchievementComponent.SteamAchievementComponent_C
// 0x0008 (0x00B8 - 0x00B0)
class USteamAchievementComponent_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SteamAchievementComponent(int32 EntryPoint);
	void UnlockAchievement(const class FString& AchievementName, class AActor* Player);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SteamAchievementComponent_C">();
	}
	static class USteamAchievementComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamAchievementComponent_C>();
	}
};
static_assert(alignof(USteamAchievementComponent_C) == 0x000008, "Wrong alignment on USteamAchievementComponent_C");
static_assert(sizeof(USteamAchievementComponent_C) == 0x0000B8, "Wrong size on USteamAchievementComponent_C");
static_assert(offsetof(USteamAchievementComponent_C, UberGraphFrame) == 0x0000B0, "Member 'USteamAchievementComponent_C::UberGraphFrame' has a wrong offset!");

}

