#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Attachment_scope_base

#include "Basic.hpp"


namespace SDK::Params
{

// Function Attachment_scope_base.Attachment_scope_base_C.ExecuteUbergraph_Attachment_scope_base
// 0x0004 (0x0004 - 0x0000)
struct Attachment_scope_base_C_ExecuteUbergraph_Attachment_scope_base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Attachment_scope_base_C_ExecuteUbergraph_Attachment_scope_base) == 0x000004, "Wrong alignment on Attachment_scope_base_C_ExecuteUbergraph_Attachment_scope_base");
static_assert(sizeof(Attachment_scope_base_C_ExecuteUbergraph_Attachment_scope_base) == 0x000004, "Wrong size on Attachment_scope_base_C_ExecuteUbergraph_Attachment_scope_base");
static_assert(offsetof(Attachment_scope_base_C_ExecuteUbergraph_Attachment_scope_base, EntryPoint) == 0x000000, "Member 'Attachment_scope_base_C_ExecuteUbergraph_Attachment_scope_base::EntryPoint' has a wrong offset!");

}

