#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HouseBase

#include "Basic.hpp"

#include "HouseBase_classes.hpp"
#include "HouseBase_parameters.hpp"


namespace SDK
{

// Function HouseBase.HouseBase_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AHouseBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HouseBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

