#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadoutAppearanceUI

#include "Basic.hpp"

#include "LoadoutAppearanceUI_classes.hpp"
#include "LoadoutAppearanceUI_parameters.hpp"


namespace SDK
{

// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.ExecuteUbergraph_LoadoutAppearanceUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutAppearanceUI_C::ExecuteUbergraph_LoadoutAppearanceUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "ExecuteUbergraph_LoadoutAppearanceUI");

	Params::LoadoutAppearanceUI_C_ExecuteUbergraph_LoadoutAppearanceUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.BndEvt__LoadoutAppearanceUI_Button_148_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadoutAppearanceUI_C::BndEvt__LoadoutAppearanceUI_Button_148_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "BndEvt__LoadoutAppearanceUI_Button_148_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.BndEvt__LoadoutAppearanceUI_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadoutAppearanceUI_C::BndEvt__LoadoutAppearanceUI_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "BndEvt__LoadoutAppearanceUI_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.RemoveloadoutCategory
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutAppearanceUI_C::RemoveloadoutCategory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "RemoveloadoutCategory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.Remove
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutAppearanceUI_C::Remove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "Remove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULoadoutAppearanceUI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.PreviewItem
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ItemInfo                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SalePrice                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutAppearanceUI_C::PreviewItem(class UClass* ItemInfo, int32 SalePrice)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "PreviewItem");

	Params::LoadoutAppearanceUI_C_PreviewItem Parms{};

	Parms.ItemInfo = ItemInfo;
	Parms.SalePrice = SalePrice;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.CancelDrag
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutAppearanceUI_C::CancelDrag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "CancelDrag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.DragItemFromCategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EShopItemCategory                       Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutAppearanceUI_C::DragItemFromCategory(EShopItemCategory Category)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "DragItemFromCategory");

	Params::LoadoutAppearanceUI_C_DragItemFromCategory Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.ChangeCategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EShopItemCategory                       Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutAppearanceUI_C::ChangeCategory(EShopItemCategory Category)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "ChangeCategory");

	Params::LoadoutAppearanceUI_C_ChangeCategory Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.RefreshInventory
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutAppearanceUI_C::RefreshInventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "RefreshInventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutAppearanceUI.LoadoutAppearanceUI_C.ChangeSkinColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UMaterialInterface*               SkinColor                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutAppearanceUI_C::ChangeSkinColor(int32 Amount, class UMaterialInterface** SkinColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutAppearanceUI_C", "ChangeSkinColor");

	Params::LoadoutAppearanceUI_C_ChangeSkinColor Parms{};

	Parms.Amount = Amount;

	UObject::ProcessEvent(Func, &Parms);

	if (SkinColor != nullptr)
		*SkinColor = Parms.SkinColor;
}

}

