#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadoutUI

#include "Basic.hpp"

#include "LoadoutUI_classes.hpp"
#include "LoadoutUI_parameters.hpp"


namespace SDK
{

// Function LoadoutUI.LoadoutUI_C.ExecuteUbergraph_LoadoutUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutUI_C::ExecuteUbergraph_LoadoutUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ExecuteUbergraph_LoadoutUI");

	Params::LoadoutUI_C_ExecuteUbergraph_LoadoutUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutUI.LoadoutUI_C.ViewAppearance
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::ViewAppearance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ViewAppearance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.ViewTools
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::ViewTools()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ViewTools");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.BndEvt__LoadoutUI_LoadoutDown_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadoutUI_C::BndEvt__LoadoutUI_LoadoutDown_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "BndEvt__LoadoutUI_LoadoutDown_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.BndEvt__LoadoutUI_LoadoutUp_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadoutUI_C::BndEvt__LoadoutUI_LoadoutUp_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "BndEvt__LoadoutUI_LoadoutUp_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.UnhighlightAll
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::UnhighlightAll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "UnhighlightAll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.HighlightButton
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UButton*                          Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutUI_C::HighlightButton(class UButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "HighlightButton");

	Params::LoadoutUI_C_HighlightButton Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutUI.LoadoutUI_C.ViewDefault
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::ViewDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ViewDefault");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.AddCategories
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<EShopItemCategory>               Categories                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ULoadoutUI_C::AddCategories(const TArray<EShopItemCategory>& Categories)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "AddCategories");

	Params::LoadoutUI_C_AddCategories Parms{};

	Parms.Categories = std::move(Categories);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutUI.LoadoutUI_C.ChangeCategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EShopItemCategory                       Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutUI_C::ChangeCategory(EShopItemCategory Category)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ChangeCategory");

	Params::LoadoutUI_C_ChangeCategory Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutUI.LoadoutUI_C.ShowweaponUI
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::ShowweaponUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ShowweaponUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.hideLoadoutCategories
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::HideLoadoutCategories()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "hideLoadoutCategories");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.RemoveAllWorldPostitionInventoryItems
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::RemoveAllWorldPostitionInventoryItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "RemoveAllWorldPostitionInventoryItems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.ShowInventoryCategory
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EShopItemCategory                       Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutUI_C::ShowInventoryCategory(EShopItemCategory Category)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ShowInventoryCategory");

	Params::LoadoutUI_C_ShowInventoryCategory Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutUI.LoadoutUI_C.BndEvt__LoadoutUI_Appearence_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadoutUI_C::BndEvt__LoadoutUI_Appearence_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "BndEvt__LoadoutUI_Appearence_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.BndEvt__LoadoutUI_Weapons_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadoutUI_C::BndEvt__LoadoutUI_Weapons_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "BndEvt__LoadoutUI_Weapons_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.BndEvt__LoadoutUI_Tools_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULoadoutUI_C::BndEvt__LoadoutUI_Tools_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "BndEvt__LoadoutUI_Tools_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.RefreshInventory
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::RefreshInventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "RefreshInventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.ShowFullInventory
// (BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::ShowFullInventory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "ShowFullInventory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.Remove
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::Remove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "Remove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULoadoutUI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.PreviewItem
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ItemInfo                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SalePrice                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutUI_C::PreviewItem(class UClass* ItemInfo, int32 SalePrice)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "PreviewItem");

	Params::LoadoutUI_C_PreviewItem Parms{};

	Parms.ItemInfo = ItemInfo;
	Parms.SalePrice = SalePrice;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutUI.LoadoutUI_C.CancelDrag
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::CancelDrag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "CancelDrag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.DragItemFromCategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EShopItemCategory                       Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoadoutUI_C::DragItemFromCategory(EShopItemCategory Category)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "DragItemFromCategory");

	Params::LoadoutUI_C_DragItemFromCategory Parms{};

	Parms.Category = Category;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadoutUI.LoadoutUI_C.RemoveloadoutCategory
// (Public, BlueprintCallable, BlueprintEvent)

void ULoadoutUI_C::RemoveloadoutCategory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "RemoveloadoutCategory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadoutUI.LoadoutUI_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText ULoadoutUI_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadoutUI_C", "GetText_0");

	Params::LoadoutUI_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

