#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadoutWeaponsUI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "ShopItemCategory_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LoadoutWeaponsUI.LoadoutWeaponsUI_C
// 0x0008 (0x0268 - 0x0260)
class ULoadoutWeaponsUI_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_LoadoutWeaponsUI(int32 EntryPoint);
	void Remove();
	void RemoveloadoutCategory();
	void Construct();
	void PreviewItem(class UClass* ItemInfo, int32 SalePrice);
	void CancelDrag();
	void DragItemFromCategory(EShopItemCategory Category);
	void ChangeCategory(EShopItemCategory Category);
	void RefreshInventory();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LoadoutWeaponsUI_C">();
	}
	static class ULoadoutWeaponsUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoadoutWeaponsUI_C>();
	}
};
static_assert(alignof(ULoadoutWeaponsUI_C) == 0x000008, "Wrong alignment on ULoadoutWeaponsUI_C");
static_assert(sizeof(ULoadoutWeaponsUI_C) == 0x000268, "Wrong size on ULoadoutWeaponsUI_C");
static_assert(offsetof(ULoadoutWeaponsUI_C, UberGraphFrame) == 0x000260, "Member 'ULoadoutWeaponsUI_C::UberGraphFrame' has a wrong offset!");

}

