#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mask_Kerchief

#include "Basic.hpp"

#include "Mask_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mask_Kerchief.Mask_Kerchief_C
// 0x0000 (0x0230 - 0x0230)
class AMask_Kerchief_C final : public AMask_base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Mask_Kerchief_C">();
	}
	static class AMask_Kerchief_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMask_Kerchief_C>();
	}
};
static_assert(alignof(AMask_Kerchief_C) == 0x000008, "Wrong alignment on AMask_Kerchief_C");
static_assert(sizeof(AMask_Kerchief_C) == 0x000230, "Wrong size on AMask_Kerchief_C");

}

