#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_hair_base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "NPCClothing_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_hair_base.NPC_hair_base_C
// 0x0010 (0x0268 - 0x0258)
class ANPC_hair_base_C : public ANPCClothing_base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_NPC_hair_base_C;                    // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   HairMesh;                                          // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void DecideColors();
	void ApplyClothing();
	void ExecuteUbergraph_NPC_hair_base(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPC_hair_base_C">();
	}
	static class ANPC_hair_base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_hair_base_C>();
	}
};
static_assert(alignof(ANPC_hair_base_C) == 0x000008, "Wrong alignment on ANPC_hair_base_C");
static_assert(sizeof(ANPC_hair_base_C) == 0x000268, "Wrong size on ANPC_hair_base_C");
static_assert(offsetof(ANPC_hair_base_C, UberGraphFrame_NPC_hair_base_C) == 0x000258, "Member 'ANPC_hair_base_C::UberGraphFrame_NPC_hair_base_C' has a wrong offset!");
static_assert(offsetof(ANPC_hair_base_C, HairMesh) == 0x000260, "Member 'ANPC_hair_base_C::HairMesh' has a wrong offset!");

}

