#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Police_Shield

#include "Basic.hpp"

#include "NPC_Police_Shield_classes.hpp"
#include "NPC_Police_Shield_parameters.hpp"


namespace SDK
{

// Function NPC_Police_Shield.NPC_Police_Shield_C.ExecuteUbergraph_NPC_Police_Shield
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Police_Shield_C::ExecuteUbergraph_NPC_Police_Shield(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Police_Shield_C", "ExecuteUbergraph_NPC_Police_Shield");

	Params::NPC_Police_Shield_C_ExecuteUbergraph_NPC_Police_Shield Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Police_Shield.NPC_Police_Shield_C.DropShieldOnDeath
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Police_Shield_C::DropShieldOnDeath(class AActor* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Police_Shield_C", "DropShieldOnDeath");

	Params::NPC_Police_Shield_C_DropShieldOnDeath Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Police_Shield.NPC_Police_Shield_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_Police_Shield_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Police_Shield_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

