#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPCClothing_Shoes

#include "Basic.hpp"

#include "NPCClothing_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPCClothing_Shoes.NPCClothing_Shoes_C
// 0x0000 (0x0258 - 0x0258)
class ANPCClothing_Shoes_C final : public ANPCClothing_base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPCClothing_Shoes_C">();
	}
	static class ANPCClothing_Shoes_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPCClothing_Shoes_C>();
	}
};
static_assert(alignof(ANPCClothing_Shoes_C) == 0x000008, "Wrong alignment on ANPCClothing_Shoes_C");
static_assert(sizeof(ANPCClothing_Shoes_C) == 0x000258, "Wrong size on ANPCClothing_Shoes_C");

}

