#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerOverview

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerOverview.PlayerOverview_C
// 0x0010 (0x0270 - 0x0260)
class UPlayerOverview_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           PlayersBox;                                        // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PlayerOverview(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerOverview_C">();
	}
	static class UPlayerOverview_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerOverview_C>();
	}
};
static_assert(alignof(UPlayerOverview_C) == 0x000008, "Wrong alignment on UPlayerOverview_C");
static_assert(sizeof(UPlayerOverview_C) == 0x000270, "Wrong size on UPlayerOverview_C");
static_assert(offsetof(UPlayerOverview_C, UberGraphFrame) == 0x000260, "Member 'UPlayerOverview_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UPlayerOverview_C, PlayersBox) == 0x000268, "Member 'UPlayerOverview_C::PlayersBox' has a wrong offset!");

}

