#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PoliceHelmet

#include "Basic.hpp"

#include "PoliceHelmet_classes.hpp"
#include "PoliceHelmet_parameters.hpp"


namespace SDK
{

// Function PoliceHelmet.PoliceHelmet_C.HelmetDestroyed__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void APoliceHelmet_C::HelmetDestroyed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PoliceHelmet_C", "HelmetDestroyed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PoliceHelmet.PoliceHelmet_C.ExecuteUbergraph_PoliceHelmet
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APoliceHelmet_C::ExecuteUbergraph_PoliceHelmet(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PoliceHelmet_C", "ExecuteUbergraph_PoliceHelmet");

	Params::PoliceHelmet_C_ExecuteUbergraph_PoliceHelmet Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PoliceHelmet.PoliceHelmet_C.LooseHealth
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APoliceHelmet_C::LooseHealth(int32 Amount, class AActor* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PoliceHelmet_C", "LooseHealth");

	Params::PoliceHelmet_C_LooseHealth Parms{};

	Parms.Amount = Amount;
	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PoliceHelmet.PoliceHelmet_C.BndEvt__PoliceHelmet_DamageComponent_K2Node_ComponentBoundEvent_0_Damage__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Bone                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          HitLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          StartLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Instigator_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APoliceHelmet_C::BndEvt__PoliceHelmet_DamageComponent_K2Node_ComponentBoundEvent_0_Damage__DelegateSignature(int32 Amount, class FName Bone, const struct FVector& HitLocation, const struct FVector& StartLocation, class AActor* Instigator_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PoliceHelmet_C", "BndEvt__PoliceHelmet_DamageComponent_K2Node_ComponentBoundEvent_0_Damage__DelegateSignature");

	Params::PoliceHelmet_C_BndEvt__PoliceHelmet_DamageComponent_K2Node_ComponentBoundEvent_0_Damage__DelegateSignature Parms{};

	Parms.Amount = Amount;
	Parms.Bone = Bone;
	Parms.HitLocation = std::move(HitLocation);
	Parms.StartLocation = std::move(StartLocation);
	Parms.Instigator_0 = Instigator_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PoliceHelmet.PoliceHelmet_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APoliceHelmet_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PoliceHelmet_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

