#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PowerboxDefuser_AnimBP

#include "Basic.hpp"

#include "PowerboxDefuser_AnimBP_classes.hpp"
#include "PowerboxDefuser_AnimBP_parameters.hpp"


namespace SDK
{

// Function PowerboxDefuser_AnimBP.PowerboxDefuser_AnimBP_C.ExecuteUbergraph_PowerboxDefuser_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerboxDefuser_AnimBP_C::ExecuteUbergraph_PowerboxDefuser_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerboxDefuser_AnimBP_C", "ExecuteUbergraph_PowerboxDefuser_AnimBP");

	Params::PowerboxDefuser_AnimBP_C_ExecuteUbergraph_PowerboxDefuser_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerboxDefuser_AnimBP.PowerboxDefuser_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerboxDefuser_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerboxDefuser_AnimBP_C", "BlueprintUpdateAnimation");

	Params::PowerboxDefuser_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerboxDefuser_AnimBP.PowerboxDefuser_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UPowerboxDefuser_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerboxDefuser_AnimBP_C", "AnimGraph");

	Params::PowerboxDefuser_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

