#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Rifle_LC4

#include "Basic.hpp"

#include "GunBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Rifle_LC4.Rifle_LC4_C
// 0x0038 (0x0348 - 0x0310)
class ARifle_LC4_C final : public AGunBase_C
{
public:
	class UStaticMeshComponent*                   Scope_front;                                       // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Wep_Mod_A_Rail;                                 // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Trigger;                                           // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Wep_Mod_A_handle;                               // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Wep_Mod_A_Stock;                                // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Wep_Mod_A_Barrel;                               // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Wep_Mod_A_Handguard_01;                         // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Rifle_LC4_C">();
	}
	static class ARifle_LC4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARifle_LC4_C>();
	}
};
static_assert(alignof(ARifle_LC4_C) == 0x000008, "Wrong alignment on ARifle_LC4_C");
static_assert(sizeof(ARifle_LC4_C) == 0x000348, "Wrong size on ARifle_LC4_C");
static_assert(offsetof(ARifle_LC4_C, Scope_front) == 0x000310, "Member 'ARifle_LC4_C::Scope_front' has a wrong offset!");
static_assert(offsetof(ARifle_LC4_C, SM_Wep_Mod_A_Rail) == 0x000318, "Member 'ARifle_LC4_C::SM_Wep_Mod_A_Rail' has a wrong offset!");
static_assert(offsetof(ARifle_LC4_C, Trigger) == 0x000320, "Member 'ARifle_LC4_C::Trigger' has a wrong offset!");
static_assert(offsetof(ARifle_LC4_C, SM_Wep_Mod_A_handle) == 0x000328, "Member 'ARifle_LC4_C::SM_Wep_Mod_A_handle' has a wrong offset!");
static_assert(offsetof(ARifle_LC4_C, SM_Wep_Mod_A_Stock) == 0x000330, "Member 'ARifle_LC4_C::SM_Wep_Mod_A_Stock' has a wrong offset!");
static_assert(offsetof(ARifle_LC4_C, SM_Wep_Mod_A_Barrel) == 0x000338, "Member 'ARifle_LC4_C::SM_Wep_Mod_A_Barrel' has a wrong offset!");
static_assert(offsetof(ARifle_LC4_C, SM_Wep_Mod_A_Handguard_01) == 0x000340, "Member 'ARifle_LC4_C::SM_Wep_Mod_A_Handguard_01' has a wrong offset!");

}

