#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scope_MarkmanHunter_LongRifle

#include "Basic.hpp"

#include "Scope_MarkmanHunter_LongRifle_classes.hpp"
#include "Scope_MarkmanHunter_LongRifle_parameters.hpp"


namespace SDK
{

// Function Scope_MarkmanHunter_LongRifle.Scope_MarkmanHunter_LongRifle_C.ExecuteUbergraph_Scope_MarkmanHunter_LongRifle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AScope_MarkmanHunter_LongRifle_C::ExecuteUbergraph_Scope_MarkmanHunter_LongRifle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scope_MarkmanHunter_LongRifle_C", "ExecuteUbergraph_Scope_MarkmanHunter_LongRifle");

	Params::Scope_MarkmanHunter_LongRifle_C_ExecuteUbergraph_Scope_MarkmanHunter_LongRifle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Scope_MarkmanHunter_LongRifle.Scope_MarkmanHunter_LongRifle_C.ScopeOut
// (BlueprintCallable, BlueprintEvent)

void AScope_MarkmanHunter_LongRifle_C::ScopeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scope_MarkmanHunter_LongRifle_C", "ScopeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Scope_MarkmanHunter_LongRifle.Scope_MarkmanHunter_LongRifle_C.ScopeIn
// (BlueprintCallable, BlueprintEvent)

void AScope_MarkmanHunter_LongRifle_C::ScopeIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scope_MarkmanHunter_LongRifle_C", "ScopeIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Scope_MarkmanHunter_LongRifle.Scope_MarkmanHunter_LongRifle_C.SetupScope
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void AScope_MarkmanHunter_LongRifle_C::SetupScope()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scope_MarkmanHunter_LongRifle_C", "SetupScope");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Scope_MarkmanHunter_LongRifle.Scope_MarkmanHunter_LongRifle_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AScope_MarkmanHunter_LongRifle_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scope_MarkmanHunter_LongRifle_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

