#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteamFriend_child

#include "Basic.hpp"

#include "SteamFriend_child_classes.hpp"
#include "SteamFriend_child_parameters.hpp"


namespace SDK
{

// Function SteamFriend_child.SteamFriend_child_C.ExecuteUbergraph_SteamFriend_child
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USteamFriend_child_C::ExecuteUbergraph_SteamFriend_child(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "ExecuteUbergraph_SteamFriend_child");

	Params::SteamFriend_child_C_ExecuteUbergraph_SteamFriend_child Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SteamFriend_child.SteamFriend_child_C.BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USteamFriend_child_C::BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SteamFriend_child.SteamFriend_child_C.BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USteamFriend_child_C::BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SteamFriend_child.SteamFriend_child_C.BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USteamFriend_child_C::BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "BndEvt__SteamFriend_child_Button_238_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SteamFriend_child.SteamFriend_child_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USteamFriend_child_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SteamFriend_child.SteamFriend_child_C.SetAvatar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USteamFriend_child_C::SetAvatar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "SetAvatar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SteamFriend_child.SteamFriend_child_C.SetName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USteamFriend_child_C::SetName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "SetName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SteamFriend_child.SteamFriend_child_C.GetColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor USteamFriend_child_C::GetColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "GetColor");

	Params::SteamFriend_child_C_GetColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SteamFriend_child.SteamFriend_child_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility USteamFriend_child_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SteamFriend_child_C", "GetVisibility_0");

	Params::SteamFriend_child_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

