#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Suppressor_Rifle

#include "Basic.hpp"

#include "Attachment_Barrel_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Suppressor_Rifle.Suppressor_Rifle_C
// 0x0000 (0x0260 - 0x0260)
class ASuppressor_Rifle_C final : public AAttachment_Barrel_base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Suppressor_Rifle_C">();
	}
	static class ASuppressor_Rifle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASuppressor_Rifle_C>();
	}
};
static_assert(alignof(ASuppressor_Rifle_C) == 0x000008, "Wrong alignment on ASuppressor_Rifle_C");
static_assert(sizeof(ASuppressor_Rifle_C) == 0x000260, "Wrong size on ASuppressor_Rifle_C");

}

