#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ToolprogressUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function ToolprogressUI.ToolprogressUI_C.GetPercent_0
// 0x0014 (0x0014 - 0x0000)
struct ToolprogressUI_C_GetPercent_0 final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ToolprogressUI_C_GetPercent_0) == 0x000004, "Wrong alignment on ToolprogressUI_C_GetPercent_0");
static_assert(sizeof(ToolprogressUI_C_GetPercent_0) == 0x000014, "Wrong size on ToolprogressUI_C_GetPercent_0");
static_assert(offsetof(ToolprogressUI_C_GetPercent_0, ReturnValue) == 0x000000, "Member 'ToolprogressUI_C_GetPercent_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(ToolprogressUI_C_GetPercent_0, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'ToolprogressUI_C_GetPercent_0::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ToolprogressUI_C_GetPercent_0, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000008, "Member 'ToolprogressUI_C_GetPercent_0::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ToolprogressUI_C_GetPercent_0, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x00000C, "Member 'ToolprogressUI_C_GetPercent_0::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ToolprogressUI_C_GetPercent_0, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000010, "Member 'ToolprogressUI_C_GetPercent_0::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");

}

