#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponBagSpawnPoint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeaponBagSpawnPoint.WeaponBagSpawnPoint_C
// 0x0020 (0x0240 - 0x0220)
class AWeaponBagSpawnPoint_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Direction;                                         // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WeaponBagSpawnPoint(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WeaponBagSpawnPoint_C">();
	}
	static class AWeaponBagSpawnPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeaponBagSpawnPoint_C>();
	}
};
static_assert(alignof(AWeaponBagSpawnPoint_C) == 0x000008, "Wrong alignment on AWeaponBagSpawnPoint_C");
static_assert(sizeof(AWeaponBagSpawnPoint_C) == 0x000240, "Wrong size on AWeaponBagSpawnPoint_C");
static_assert(offsetof(AWeaponBagSpawnPoint_C, UberGraphFrame) == 0x000220, "Member 'AWeaponBagSpawnPoint_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AWeaponBagSpawnPoint_C, StaticMesh) == 0x000228, "Member 'AWeaponBagSpawnPoint_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(AWeaponBagSpawnPoint_C, Direction) == 0x000230, "Member 'AWeaponBagSpawnPoint_C::Direction' has a wrong offset!");
static_assert(offsetof(AWeaponBagSpawnPoint_C, DefaultSceneRoot) == 0x000238, "Member 'AWeaponBagSpawnPoint_C::DefaultSceneRoot' has a wrong offset!");

}

